### ISSUE TITLE
Add a placeholder

### ISSUE THREAD

**Issue by ghost** [itkpi/itkpi-blog-theme#4]
Добавить плейсхолдер к форме в ["Запропонувати подiю"](http://itkpi.pp.ua/events/suggest/) для облегчения дальнейшего редактирования: будет меньше всяких вольностей в предложке.

**Comment by MaxymVlasov** [comment]
@yulian-khlevnoy Готово. Заповнюй - http://itkpi.pp.ua/events_design/
